#!/bin/bash
echo playlist url?
read playlist
echo email?
read -s email
echo password?
read -s password
youtube-dl -x --audio-quality 0 --download-archive archive.txt --audio-format "mp3" ${playlist} --username ${email} --password ${password} -o "%(title)s.%(ext)s"
